# ComfyUI ModelScope API Plugin
from .nodes.modelscope_api_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MAIN, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MAIN
from .nodes.modelscope_api_model_presets_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MODEL, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MODEL
from .nodes.modelscope_api_lora_presets_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_LORA, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_LORA

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_MAIN,
    **NODE_CLASS_MAPPINGS_MODEL,
    **NODE_CLASS_MAPPINGS_LORA
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_MAIN,
    **NODE_DISPLAY_NAME_MAPPINGS_MODEL,
    **NODE_DISPLAY_NAME_MAPPINGS_LORA
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']